n1 = input('Digite algo: ')
print('O tipo primitivo é', type(n1))
print('Só tem espaços?', n1.isspace())
print('É um número?', n1.isnumeric())
print('É alfabédico?', n1.isalpha())
print('É alfanumérico?', n1.isalnum())
print('Está em maiúscula?', n1.isupper())
print('Está em minúscula?', n1.isalnum())
print('Está captalizada?', n1.istitle())