n = input('Digite algo: ')
print ('O tipo primitivo desse valor é: ',type(n))
print ('Só tem espaços: ', n.isspace())
print ('É um número: ', n.isnumeric())
print ('É alfabético? ', n.isalpha())
print ('É numérico? ', n. isalnum())
print ('Está em maiúscula? ', n.isupper())
print ('Está em minuscula? ', n.islower())
print ('Está captalizado: ', n.istitle())

